[package]
name = "viper_analyze"
version = "0.1.0"
edition = "2024"

[dependencies]
viper_common = { path = "../viper_common" }
viper_lex = { path = "../viper_lex" }
viper_ast = { path = "../viper_ast" }
